# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todos_api_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: todos_api_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: todos-api_production
  username: todos-api
  password: <%= ENV['TODOS-API_DATABASE_PASSWORD'] %>